"""add device pairing columns

Revision ID: d6579c860c3c
Revises: 4af4c341d50e
Create Date: 2026-03-28 16:58:47.231757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6579c860c3c'
down_revision: Union[str, None] = '4af4c341d50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('registration_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('registration_expires')
        batch_op.drop_column('registration_code')

    # ### end Alembic commands ###
