#!/usr/bin/env python3
"""TinySignage GPIO Bridge — interactive installer.

Usage:
    sudo python3 install.py                # Interactive install (recommended)
    sudo python3 install.py --non-interactive  # Defaults: 3 GPIO buttons, no joystick

Sets up apt packages, Python venv, udev rules, groups, config.yaml,
and systemd service. Requires Python 3.9+, stdlib only (no PyYAML).
"""

import argparse
import os
import subprocess
import sys

# =========================================================================
# Constants
# =========================================================================

BRIDGE_DIR = "/opt/tinysignage/tinysignage-bridge"
SERVICE_USER = "tinysignage"
SERVICE_FILE = "/etc/systemd/system/tinysignage-bridge.service"
UDEV_RULE = "/etc/udev/rules.d/99-input.rules"
MAIN_CONFIG = "/opt/tinysignage/config.yaml"
BRIDGE_CONFIG = os.path.join(BRIDGE_DIR, "config.yaml")
CERT_DIR = "/opt/tinysignage/certs"

# --- Pin presets ----------------------------------------------------------

PIN_PRESETS = {
    "3-button": [
        {"pin": 17, "name": "Button 1"},
        {"pin": 27, "name": "Button 2"},
        {"pin": 22, "name": "Button 3"},
    ],
    "1-button": [
        {"pin": 17, "name": "Button 1"},
    ],
    "none": [],
}

# --- Systemd unit ---------------------------------------------------------

SYSTEMD_UNIT = """\
[Unit]
Description=TinySignage GPIO Bridge
After=network.target

[Service]
Type=simple
User={user}
WorkingDirectory={bridge_dir}
ExecStart={bridge_dir}/venv/bin/python bridge.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

TOTAL_STEPS = 5


# =========================================================================
# Helpers (matching main install.py style)
# =========================================================================

def run_cmd(cmd, cwd=None, check=True, capture=False):
    """Run a subprocess. On failure (if check), print error and exit."""
    kwargs = {"cwd": cwd}
    if capture:
        kwargs["capture_output"] = True
        kwargs["text"] = True
    try:
        result = subprocess.run(cmd, **kwargs)
    except FileNotFoundError:
        if check:
            error_exit(f"Command not found: {cmd[0]}")
        return None
    if check and result.returncode != 0:
        cmd_str = " ".join(str(c) for c in cmd)
        msg = f"Command failed: {cmd_str}"
        if capture and result.stderr:
            msg += f"\n{result.stderr.strip()}"
        error_exit(msg)
    return result


def run_as_user(user, cmd, cwd=None, check=True, capture=False):
    """Run a command as a different user via runuser (Linux only)."""
    return run_cmd(
        ["runuser", "-u", user, "--"] + list(cmd),
        cwd=cwd, check=check, capture=capture,
    )


def prompt_yn(message, default=True):
    """Prompt for yes/no."""
    suffix = " [Y/n]: " if default else " [y/N]: "
    try:
        value = input(message + suffix).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(1)
    if not value:
        return default
    return value in ("y", "yes")


def prompt_choice(message, options, default=1):
    """Prompt for a numbered choice. Returns 1-based index."""
    print(f"\n{message}\n")
    for i, option in enumerate(options, 1):
        print(f"  {i}. {option}")
    print()
    while True:
        try:
            value = input(f"Choice [{default}]: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            sys.exit(1)
        if not value:
            return default
        if value.isdigit() and 1 <= int(value) <= len(options):
            return int(value)
        print(f"  Please enter a number from 1 to {len(options)}.")


def step(number, total, message):
    print(f"\n[{number}/{total}] {message}")


def info(message):
    print(f"  {message}")


def warn(message):
    print(f"  WARNING: {message}")


def error_exit(message):
    print(f"\nERROR: {message}", file=sys.stderr)
    sys.exit(1)


# =========================================================================
# Config generation
# =========================================================================

def detect_tls():
    """Check if the main TinySignage server has TLS enabled."""
    try:
        with open(MAIN_CONFIG, "r") as f:
            for line in f:
                if "enabled: true" in line:
                    return True
    except FileNotFoundError:
        pass
    return False


def build_config_yaml(pins_preset, joystick_enabled, tls_enabled):
    """Build config.yaml content as a string (no PyYAML dependency)."""
    lines = [
        "# TinySignage GPIO Bridge — Pin Configuration",
        "# Generated by install.py — edit freely, then restart the service.",
        "",
        "websocket_port: 8765",
        "",
    ]

    pins = PIN_PRESETS[pins_preset]
    if pins:
        lines.append("pins:")
        for p in pins:
            lines.append(f'  - pin: {p["pin"]}')
            lines.append(f'    name: "{p["name"]}"')
            lines.append("    pull_up: true")
            lines.append("    bounce_time: 0.2")
    else:
        lines.append("pins: []")

    lines.append("")
    lines.append("# Joystick / gamepad support via evdev")
    lines.append("# Requires: pip install evdev, Linux only, user must be in 'input' group")
    lines.append("joystick:")
    lines.append(f"  enabled: {'true' if joystick_enabled else 'false'}")
    lines.append("  dead_zone: 0.1         # Ignore axis values below this (0.0-1.0)")
    lines.append("  axis_threshold: 0.5    # Axis value that triggers an event (0.0-1.0)")
    lines.append("  poll_interval: 0.01    # Seconds between device scans")

    lines.append("")
    lines.append("# TLS / WSS support — required when TinySignage uses HTTPS")
    lines.append("# Uses the same self-signed cert generated by the main TinySignage server.")
    lines.append("tls:")
    lines.append(f"  enabled: {'true' if tls_enabled else 'false'}")
    lines.append(f"  cert_file: {CERT_DIR}/cert.pem")
    lines.append(f"  key_file: {CERT_DIR}/key.pem")
    lines.append("")

    return "\n".join(lines)


# =========================================================================
# Interactive wizard
# =========================================================================

def run_wizard():
    """Ask 2-3 questions and return (pins_preset, joystick_enabled)."""
    print("=" * 48)
    print("  TinySignage GPIO Bridge Installer")
    print("=" * 48)
    print()
    print("The GPIO Bridge connects physical buttons and USB gamepads")
    print("to your signage player. Press a button, change the display.")
    print()

    # Q1: GPIO buttons?
    use_gpio = prompt_yn("Will you use physical buttons (GPIO)?", default=True)
    if use_gpio:
        choice = prompt_choice(
            "How many buttons?",
            [
                "Three buttons (recommended) — Pins 17, 27, 22",
                "Single button — Pin 17 only",
            ],
            default=1,
        )
        pins_preset = "3-button" if choice == 1 else "1-button"
        print()
        info("Wiring: connect each button between its GPIO pin and any GND pin.")
        info("No resistors needed — the bridge uses internal pull-ups.")
    else:
        pins_preset = "none"

    # Q2: Joystick?
    print()
    joystick_enabled = prompt_yn(
        "Will you use a USB joystick or gamepad?", default=False,
    )
    if joystick_enabled:
        print()
        info("Plug in your gamepad before or after install — it's auto-detected.")
        info("To find button codes later, run: sudo evtest")

    return pins_preset, joystick_enabled


# =========================================================================
# Install steps
# =========================================================================

def preflight_checks():
    """Verify prerequisites before starting."""
    if os.getuid() != 0:
        error_exit("Must run as root (sudo).")

    if not os.path.isfile(os.path.join(BRIDGE_DIR, "bridge.py")):
        error_exit(
            f"bridge.py not found in {BRIDGE_DIR}\n"
            "Run the main TinySignage installer first."
        )

    try:
        subprocess.run(
            ["id", SERVICE_USER],
            capture_output=True, check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        error_exit(
            f"Service user '{SERVICE_USER}' does not exist.\n"
            "Run the main TinySignage installer first."
        )


def install_system_packages():
    """Step 1: apt-get python3-lgpio."""
    step(1, TOTAL_STEPS, "Installing system packages...")
    run_cmd(
        ["apt-get", "install", "-y", "-qq", "python3-lgpio"],
        capture=True,
    )
    info("python3-lgpio installed (GPIO pin factory for Pi 5).")


def setup_python_env():
    """Step 2: venv + pip install."""
    step(2, TOTAL_STEPS, "Setting up Python environment...")
    venv_dir = os.path.join(BRIDGE_DIR, "venv")
    run_as_user(
        SERVICE_USER,
        ["python3", "-m", "venv", "--system-site-packages", venv_dir],
    )
    pip = os.path.join(venv_dir, "bin", "pip")
    run_as_user(
        SERVICE_USER,
        [pip, "install", "--quiet", "gpiozero", "websockets", "pyyaml", "evdev"],
    )
    info("Dependencies installed.")


def setup_hardware_access():
    """Step 3: gpio/input groups, udev rule."""
    step(3, TOTAL_STEPS, "Setting up hardware access...")

    # gpio group
    result = run_cmd(["getent", "group", "gpio"], check=False, capture=True)
    if result and result.returncode == 0:
        check = run_cmd(
            ["id", "-nG", SERVICE_USER], capture=True, check=False,
        )
        if check and "gpio" not in (check.stdout or "").split():
            run_cmd(["usermod", "-aG", "gpio", SERVICE_USER])
            info(f"Added '{SERVICE_USER}' to 'gpio' group.")
        else:
            info(f"'{SERVICE_USER}' already in 'gpio' group.")

    # input group
    result = run_cmd(["getent", "group", "input"], check=False, capture=True)
    if not result or result.returncode != 0:
        run_cmd(["groupadd", "input"])
        info("Created 'input' group.")

    check = run_cmd(
        ["id", "-nG", SERVICE_USER], capture=True, check=False,
    )
    if check and "input" not in (check.stdout or "").split():
        run_cmd(["usermod", "-aG", "input", SERVICE_USER])
        info(f"Added '{SERVICE_USER}' to 'input' group.")
    else:
        info(f"'{SERVICE_USER}' already in 'input' group.")

    # udev rule
    udev_line = 'KERNEL=="event*", SUBSYSTEM=="input", MODE="0664", GROUP="input"'
    needs_udev = True
    if os.path.isfile(UDEV_RULE):
        with open(UDEV_RULE, "r") as f:
            if udev_line in f.read():
                needs_udev = False
                info("udev rule already in place.")

    if needs_udev:
        with open(UDEV_RULE, "w") as f:
            f.write(udev_line + "\n")
        run_cmd(["udevadm", "control", "--reload-rules"])
        info(f"udev rule created at {UDEV_RULE}")


def configure_connection(pins_preset, joystick_enabled):
    """Step 4: TLS detect, write config.yaml."""
    step(4, TOTAL_STEPS, "Configuring connection security...")

    tls_enabled = detect_tls()
    if tls_enabled:
        info("TLS enabled (matching main server HTTPS).")
        # Ensure cert permissions
        if os.path.isdir(CERT_DIR):
            for pem in ("cert.pem", "key.pem"):
                path = os.path.join(CERT_DIR, pem)
                if os.path.isfile(path):
                    run_cmd(["chown", f"{SERVICE_USER}:{SERVICE_USER}", path],
                            check=False)
            cert = os.path.join(CERT_DIR, "cert.pem")
            key = os.path.join(CERT_DIR, "key.pem")
            if os.path.isfile(cert):
                os.chmod(cert, 0o644)
            if os.path.isfile(key):
                os.chmod(key, 0o600)
            info("Cert access verified for bridge TLS.")
    else:
        info("TLS disabled (main server not using HTTPS).")

    # Stop service before overwriting config (if already running)
    run_cmd(
        ["systemctl", "stop", "tinysignage-bridge"],
        check=False, capture=True,
    )

    config_content = build_config_yaml(pins_preset, joystick_enabled, tls_enabled)
    with open(BRIDGE_CONFIG, "w") as f:
        f.write(config_content)
    # Ensure service user can read it
    run_cmd(["chown", f"{SERVICE_USER}:{SERVICE_USER}", BRIDGE_CONFIG],
            check=False)
    info(f"Config written to {BRIDGE_CONFIG}")


def create_service():
    """Step 5: systemd unit, enable, start."""
    step(5, TOTAL_STEPS, "Creating system service...")

    unit_content = SYSTEMD_UNIT.format(
        user=SERVICE_USER,
        bridge_dir=BRIDGE_DIR,
    )
    with open(SERVICE_FILE, "w") as f:
        f.write(unit_content)

    run_cmd(["systemctl", "daemon-reload"])
    run_cmd(["systemctl", "enable", "tinysignage-bridge"], capture=True)
    run_cmd(["systemctl", "start", "tinysignage-bridge"])
    info("systemd service enabled and started.")


def print_success(pins_preset, joystick_enabled):
    """Print final summary with conditional tips."""
    print()
    print("=" * 50)
    print("  GPIO Bridge installed successfully!")
    print()
    print(f"  Status:  sudo systemctl status tinysignage-bridge")
    print(f"  Logs:    journalctl -u tinysignage-bridge -f")
    print(f"  Config:  {BRIDGE_CONFIG}")

    if pins_preset != "none":
        pins = PIN_PRESETS[pins_preset]
        pin_nums = ", ".join(str(p["pin"]) for p in pins)
        print()
        print(f"  Wiring: connect buttons on GPIO {pin_nums} to any GND pin.")
        print("  No resistors needed (internal pull-ups are on).")

    if joystick_enabled:
        print()
        print("  Gamepad: plug in any USB gamepad — it's auto-detected.")
        print("  Find button codes with: sudo evtest")

    print()
    print("  Changed config? Restart with:")
    print("    sudo systemctl restart tinysignage-bridge")
    print("=" * 50)
    print()


# =========================================================================
# Main
# =========================================================================

def main():
    parser = argparse.ArgumentParser(
        description="TinySignage GPIO Bridge installer",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Skip prompts — use defaults (3 GPIO buttons, no joystick)",
    )
    args = parser.parse_args()

    preflight_checks()

    if args.non_interactive:
        print("Installing TinySignage GPIO Bridge (non-interactive)...")
        pins_preset = "3-button"
        joystick_enabled = False
    else:
        pins_preset, joystick_enabled = run_wizard()

    install_system_packages()
    setup_python_env()
    setup_hardware_access()
    configure_connection(pins_preset, joystick_enabled)
    create_service()
    print_success(pins_preset, joystick_enabled)


if __name__ == "__main__":
    main()
